apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-config
  namespace: coldchain
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_GROUP_ID: "coldchain-ingestion"
  KAFKA_TOPICS: "coldchain.telemetry.trucks,coldchain.telemetry.rooms,coldchain.alerts"
  MONGO_URI: "mongodb://10.0.10.120:27017"
  MONGO_DB: "coldchain"